title: 极寒之域--雾之湖
author: HoshinoTented
keywords: HoshinoTented, blog, cirno
twitter: 不告诉你
email: limbolrain@gmail.com
description: >
  Hoshi no Blog
baseurl: ""
url: "http://blog.hoshino9.org"
github_username: HoshinoTented
markdown: kramdown
domain: hoshino9.org
repository: https://github.com/HoshinoTented/hoshinotented.github.io
repository_name: hoshinotented.github.io
paginate: 9
paginate_path: "blog/page:num"